### ISSUE TITLE
【申请】wendal.luatos.org

### ISSUE THREAD

**Issue by wendal** [chenxuuu/luatos.org#1]
# 申请新域名

|     项目    |                        信息                      |
|-----------|-------------------------------------|
| 域名前缀 | wendal                               |
| 指向仓库 | github.com/wendal/luatos-blog    |
| 邮箱账号 | wendal |
| 邮箱转发目标 | vt400@qq.com |

## 用途

试试博客功能

**Comment by chenxuuu** [comment]
已配置，邮箱有封验证邮件注意看下
